name: reactive_touch_spin
description: Wrapper around flutter_touch_spin to use with reactive_forms
version: 0.8.4
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  reactive_forms: ^18.0.0
  intl: ^0.20.2
  flutter_touch_spin_2:
    git:
      url: https://github.com/BenjiFarquhar/flutter_touch_spin_2.git
      ref: 0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: